server:
  port: 8080
  address: 0.0.0.0  # ??????????

spring:
  application:
    name: MyBlog

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_blog
    username: root
    password: 123456

#  mail:
#    host: smtp.163.com  # 163 ??? SMTP ???
#    port: 465  # 163 SMTP ???SSL?
#    username: pianodrum@163.com  # ?? 163 ????
#    password: DUi2SrtTndc5MayY  # ?????????????????
#    protocol: smtps
#    properties:
#      mail:
#        smtp:
#          auth: true
#          ssl:
#            enable: true
#            required: false

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

  data:
    redis:
      host: localhost
      port: 6379
      password: redis123456
      timeout: 3s        # ????
      client-type: lettuce
      lettuce:
        pool:
          enabled: true
          max-active: 10
          max-idle: 5
          min-idle: 1
          max-wait: 500ms

mybatis:
  configuration:
    map-underscore-to-camel-case: true

avatar:
  upload-path: uploads/avatar/     # 项目目录下相对路径
  access-url-prefix: http://localhost:8080/uploads/avatar/

cover:
  upload-path: uploads/cover/
  access-url-prefix: http://localhost:8080/uploads/cover/